### ISSUE TITLE
extract_data reshape ValueError

### ISSUE THREAD

**Issue by ChazzyGordon** [hbdat/cvpr20_IMCL#1]
Bug when running `python3 extract_data/extract_feature_2_TFRecords_OpenImages.py`:

```
features_v.shape: (32, 1, 1, 2048)
features.shape: (?, 1, 1, 2048)
batch no. 0
Traceback (most recent call last):
  File "extract_data/extract_feature_2_TFRecords_OpenImages.py", line 181, in <module>
    feature = np.reshape(feature, [49, 2048])
  File "<__array_function__ internals>", line 6, in reshape
  File "/usr/local/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 2048 into shape (49,2048)
```

How to solve this problem? Thank you!

**Comment by hbdat** [comment]
Thanks for spotting these missing files.

Since these files are too big for Github (probably why they are missing on github), I upload them on google drive under the following links:

`result/baseline_logistic_OpenImages.npz`
https://drive.google.com/file/d/1our5lctu-H567VjX20X9TSgiGINIAPzz/view?usp=sharing

`label_graph/graph_label_naive.npy`
https://drive.google.com/file/d/1kg0UeInk33cKadq8rEU3i-3wSm3Oq7Oh/view?usp=sharing

I have also updated the ReadMe file to include these links.

Best,
Dat

**Comment by hbdat** [comment]
Thanks for pointing out this error.

I have updated the data extraction script in my latest commit which fixes this issue.
I have also tested the script to ensure that there is no error.

Best,
Dat
